// oddsService.js — BYN fixture & odds router
// All probabilities generated by our own models — no third-party Odds API
// Returns { fixtures: [], nextFixtureDate: string | null }

const ROUTE_MAP = {
  fifa_wc:      '/api/football-model',
  euros:        '/api/football-model',
  epl:          '/api/football-model',
  laliga:       '/api/football-model',
  ucl:          '/api/football-model',
  championship:   '/api/football-model',
  league_one:     '/api/football-model',
  league_two:     '/api/football-model',
  national_league:'/api/football-model',
  nations_champ:'/api/rugby-fixtures',
  rugby_champ:  '/api/rugby-fixtures',
  six_nations:  '/api/rugby-fixtures',
  urc:          '/api/rugby-fixtures',
  super_rugby:  '/api/rugby-fixtures',
  prem_rugby:   '/api/rugby-fixtures',
  rugby_wc:     '/api/rugby-fixtures',
  f1:           null, // handled separately
  tennis:       '/api/tennis-model',
  pga:          '/api/golf-model',
  nfl:          '/api/nfl-model',
}

// ── F1 via OpenF1 ─────────────────────────────────────────────────────────────
async function fetchF1Fixtures() {
  try {
    const res = await fetch('/api/f1-fixtures')
    if (!res.ok) return { fixtures: [], nextFixtureDate: null }
    const data = await res.json()
    if (!data.race || !data.drivers?.length) return { fixtures: [], nextFixtureDate: null }
    return {
      fixtures: [{
        name: data.race.name,
        circuit: data.race.circuit,
        location: data.race.location,
        kickoff: data.race.date,
        externalId: `f1-${data.race.id}`,
        format: 'outright',
        outcomes: data.drivers.map(d => `${d.fullName} · ${d.team}`),
        probabilities: data.drivers.map(d => d.probability),
        // FIX (settlement job dependency): driverNumbers is parallel to
        // outcomes/probabilities, giving each outcome a stable numeric ID
        // (OpenF1's driver_number) instead of only a display-string label.
        // Flows through to liveFixturesToMarkets() in App.jsx as
        // market.outcomeRefs, then into market_outcomes.external_ref at
        // creation time. Without this, the auto-settlement job has no
        // reliable way to match a race winner back to a BYN outcome.
        driverNumbers: data.drivers.map(d => d.number),
        driverDetails: data.drivers,
      }],
      nextFixtureDate: data.race.date,
    }
  } catch (err) {
    console.error('Error fetching F1 fixtures:', err)
    return { fixtures: [], nextFixtureDate: null }
  }
}

// ── Generic model fetcher ─────────────────────────────────────────────────────
async function fetchFromModel(route, competitionKey) {
  try {
    const res = await fetch(`${route}?competitionKey=${competitionKey}`)
    if (!res.ok) return { fixtures: [], nextFixtureDate: null }
    const data = await res.json()

    const fixtures = (data.fixtures || []).map(f => ({
      name: f.name,
      kickoff: f.kickoff || null,
      externalId: f.externalId || null,
      outcomes: f.outcomes,
      probabilities: f.probabilities,
      format: f.format,
      stage: f.stage || null,
    }))

    // Extract next fixture date from model response
    const nextFixtureDate = data.nextFixture
      || data.nextFixtureDate
      || data.seasonOpens
      || (data.fixtures?.[0]?.kickoff)
      || null

    return { fixtures, nextFixtureDate }
  } catch (err) {
    console.error(`Error fetching from ${route}:`, err)
    return { fixtures: [], nextFixtureDate: null }
  }
}

// ── MAIN ENTRY POINT ──────────────────────────────────────────────────────────
export async function fetchUpcomingFixtures(competitionKey) {
  if (competitionKey === 'f1') return fetchF1Fixtures()

  const route = ROUTE_MAP[competitionKey]
  if (!route) return { fixtures: [], nextFixtureDate: null }

  return fetchFromModel(route, competitionKey)
}
