// oddsService.js — BYN fixture & odds router
// All probabilities generated by our own models — no third-party Odds API
//
// Routes each competition key to the appropriate model serverless function:
//   Football (intl + club) → /api/football-model
//   Rugby                  → /api/rugby-fixtures
//   F1                     → /api/f1-fixtures
//   Tennis                 → /api/tennis-model
//   Golf                   → /api/golf-model
//   NFL                    → /api/nfl-model

// ── Competition → API route mapping ──────────────────────────────────────────
const ROUTE_MAP = {
  // Football
  fifa_wc:     '/api/football-model',
  euros:       '/api/football-model',
  epl:         '/api/football-model',
  laliga:      '/api/football-model',
  ucl:         '/api/football-model',
  // Rugby
  nations_champ: '/api/rugby-fixtures',
  rugby_champ:   '/api/rugby-fixtures',
  six_nations:   '/api/rugby-fixtures',
  urc:           '/api/rugby-fixtures',
  super_rugby:   '/api/rugby-fixtures',
  prem_rugby:    '/api/rugby-fixtures',
  rugby_wc:      '/api/rugby-fixtures',
  // Motorsport
  f1:          '/api/f1-fixtures',
  // Tennis
  tennis:      '/api/tennis-model',
  // Golf
  pga:         '/api/golf-model',
  // American football
  nfl:         '/api/nfl-model',
}

// ── F1 via OpenF1 (special case — uses GET, no competitionKey param) ──────────
async function fetchF1Fixtures() {
  try {
    const res = await fetch('/api/f1-fixtures')
    if (!res.ok) return []
    const data = await res.json()
    if (!data.race || !data.drivers?.length) return []
    return [{
      name: data.race.name,
      circuit: data.race.circuit,
      location: data.race.location,
      kickoff: data.race.date,
      externalId: `f1-${data.race.id}`,
      format: 'outright',
      outcomes: data.drivers.map(d => `${d.fullName} · ${d.team}`),
      probabilities: data.drivers.map(d => d.probability),
      driverDetails: data.drivers,
    }]
  } catch (err) {
    console.error('Error fetching F1 fixtures:', err)
    return []
  }
}

// ── Generic model fetcher ────────────────────────────────────────────────────
async function fetchFromModel(route, competitionKey) {
  try {
    const url = `${route}?competitionKey=${competitionKey}`
    const res = await fetch(url)
    if (!res.ok) return []
    const data = await res.json()
    if (!data.fixtures?.length) return []
    return data.fixtures.map(f => ({
      name: f.name,
      kickoff: f.kickoff || null,
      externalId: f.externalId || null,
      outcomes: f.outcomes,
      probabilities: f.probabilities,
      format: f.format,
      stage: f.stage || null,
    }))
  } catch (err) {
    console.error(`Error fetching from ${route}:`, err)
    return []
  }
}

// ── MAIN ENTRY POINT ──────────────────────────────────────────────────────────
export async function fetchUpcomingFixtures(competitionKey) {
  // F1 uses its own special endpoint
  if (competitionKey === 'f1') {
    return fetchF1Fixtures()
  }

  const route = ROUTE_MAP[competitionKey]
  if (!route) {
    console.warn(`No model route for competition: ${competitionKey}`)
    return []
  }

  return fetchFromModel(route, competitionKey)
}
